#!/usr/bin/env bash
# Return latest tag for given package name
set -e

PACKAGE="$1"

if [[ -z "$PACKAGE" ]]; then
  echo "Error: A package name is required"
  exit 1
fi

tag_pattern="$PACKAGE-v*"
tags="$(git tag --list --sort='-*authordate' "$PACKAGE-v*")"

if [[ -z "$tags" ]]; then
  echo "Error: No tags matching pattern '$tag_pattern.'"
  exit 1
fi

last_tag="$(echo -e "$tags" | head -n 1 | grep -E 'v[0-9]+\.[0-9]+\.[0-9]+$' || true)"
if [[ -z "$last_tag" ]]; then
  echo "Error: Tag format not compatible."
  exit 1
fi

echo "$last_tag"
